version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    working_directory: ~/homeontheroute-api
    steps:
      - run:
          name: update package cache
          command: apk --no-cache update
      - run:
          name: install Docker client
          command: apk add --update docker
      - run:
          name: install AWS CLI and EB CLI
          command: |
            apk --no-cache add python py-pip && \
            pip --no-cache-dir install awscli && \
            pip --no-cache-dir install awsebcli
      # Before `checkout`, fix this CircleCI warning:
      #
      #   Warning: Either git or ssh (required by git to clone through SSH) is not installed in the image.
      #   Falling back to CircleCI's native git client but this is still an experiment feature.
      #   We highly recommend using an image that has official git and ssh installed.
      - run:
          name: install Git and SSH
          command: |
            apk add --update git
            apk add --update openssh-client
      - checkout
      - run:
          name: download latest King County Metro GTFS data
          command: |
            apk add --update curl
            curl -o metro-gtfs.zip http://metro.kingcounty.gov/gtfs/google_transit.zip
            mkdir -p priv/metro-gtfs
            (cd priv/metro-gtfs && unzip ../../metro-gtfs.zip)
      - setup_remote_docker
      - run:
          command: docker build -t homeontheroute .
      - run:
          name: log into AWS ECR
          command: eval $(aws ecr get-login --region us-west-2)
      - run:
          name: tag and push the new Docker image to ECR
          command: |
            docker tag homeontheroute:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/homeontheroute:latest
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/homeontheroute:latest
      - run:
          name: deploy latest Docker image to Elastic Beanstalk
          command: |
            git status
            eb status
            eb deploy
